[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "arabic-customer-service"
version = "1.0.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["backend*"]
